import type { INodePropertyOptions } from 'n8n-workflow';

export const INSTANCE_EVENTS = [
	'chats.delete',
	'chats.updated',
	'connection.update',
	'contacts.update',
	'contacts.upsert',
	'groups.participants.update',
	'groups.update',
	'groups.upsert',
	'history.sync',
	'identity.update',
	'labels.association',
	'labels.edit',
	'media.retry',
	'messages.delete',
	'messages.star',
	'messages.undecryptable',
	'messages.update',
	'messages.upsert',
	'news.letter',
	'presence.updated',
	'profile.picture.update',
	'qrcode.updated',
	'send.message',
	'settings.update',
	'status.instance',
	'user.about.update',
] as const;

export const CALL_EVENTS = [
	'call.upsert',
	'call.incoming',
	'call.outgoing',
	'call.ringing',
	'call.connecting',
	'call.active',
	'call.ready',
	'call.answered_elsewhere',
	'call.rejected_elsewhere',
	'call.hangup.requested',
	'call.ending',
	'call.terminate.sent',
	'call.terminate.confirmed',
	'call.terminate.retry',
	'call.terminate.failed',
	'call.ended',
	'call.ended_unconfirmed',
	'call.video.playback.started',
	'call.video.playback.completed',
	'call.video.playback.stopped',
	'call.video.playback.failed',
	'call.recording.started',
	'call.recording.completed',
	'call.recording.partial',
	'call.recording.failed',
	'call.recording.unavailable',
	'call.recording.deleted',
	'call.recording.expired',
] as const;

export const GLOBAL_EVENTS = [
	'message.batch.created',
	'message.batch.scheduled',
	'message.batch.started',
	'message.batch.window-started',
	'message.batch.waiting-window',
	'message.batch.recovered',
	'message.batch.progress',
	'message.batch.pause-requested',
	'message.batch.paused',
	'message.batch.waiting-instance',
	'message.batch.resumed',
	'message.batch.stop-requested',
	'message.batch.stopped',
	'message.batch.interrupted',
	'message.batch.completed',
	'message.batch.completed-with-errors',
	'message.batch.item.failed',
	'message.batch.item.unknown',
] as const;

export type InstanceEvent = (typeof INSTANCE_EVENTS)[number];
export type CallEvent = (typeof CALL_EVENTS)[number];
export type GlobalEvent = (typeof GLOBAL_EVENTS)[number];

export const INSTANCE_EVENT_OPTIONS: INodePropertyOptions[] = [
	{ name: 'Message Received', value: 'messages.upsert', description: 'A message was created or received' },
	{ name: 'Message Updated', value: 'messages.update', description: 'A message was updated' },
	{ name: 'Message Deleted', value: 'messages.delete', description: 'A message was deleted' },
	{ name: 'Message Starred', value: 'messages.star', description: 'A message was starred or unstarred' },
	{ name: 'Message Undecryptable', value: 'messages.undecryptable', description: 'A message could not be decrypted' },
	{ name: 'Send Message Result', value: 'send.message', description: 'A send message operation emitted an event' },
	{ name: 'Chat Updated', value: 'chats.updated', description: 'A chat was updated' },
	{ name: 'Chat Deleted', value: 'chats.delete', description: 'A chat was deleted' },
	{ name: 'Presence Updated', value: 'presence.updated', description: 'A contact presence changed' },
	{ name: 'Contact Updated', value: 'contacts.update', description: 'A contact was updated' },
	{ name: 'Contact Created or Updated', value: 'contacts.upsert', description: 'A contact was created or updated' },
	{ name: 'Group Updated', value: 'groups.update', description: 'A group was updated' },
	{ name: 'Group Created or Updated', value: 'groups.upsert', description: 'A group was created or updated' },
	{ name: 'Group Participants Updated', value: 'groups.participants.update', description: 'Group participants changed' },
	{ name: 'Connection Updated', value: 'connection.update', description: 'The instance connection changed' },
	{ name: 'QR Code Updated', value: 'qrcode.updated', description: 'A pairing QR code changed' },
	{ name: 'Instance Status Updated', value: 'status.instance', description: 'The instance status changed' },
	{ name: 'History Synced', value: 'history.sync', description: 'Message history was synced' },
	{ name: 'Identity Updated', value: 'identity.update', description: 'Identity information changed' },
	{ name: 'Label Association Changed', value: 'labels.association', description: 'A label association changed' },
	{ name: 'Label Edited', value: 'labels.edit', description: 'A label was edited' },
	{ name: 'Media Retry', value: 'media.retry', description: 'A media retry event occurred' },
	{ name: 'Newsletter Event', value: 'news.letter', description: 'A newsletter event occurred' },
	{ name: 'Profile Picture Updated', value: 'profile.picture.update', description: 'A profile picture changed' },
	{ name: 'Settings Updated', value: 'settings.update', description: 'Instance settings changed' },
	{ name: 'User About Updated', value: 'user.about.update', description: 'A user about text changed' },
];

export const CALL_EVENT_OPTIONS: INodePropertyOptions[] = [
	{ name: 'Call Upsert', value: 'call.upsert', description: 'A call was created or updated' },
	{ name: 'Incoming Call', value: 'call.incoming', description: 'An incoming call was received' },
	{ name: 'Outgoing Call', value: 'call.outgoing', description: 'An outgoing call was started' },
	{ name: 'Call Ringing', value: 'call.ringing', description: 'A call is ringing' },
	{ name: 'Call Connecting', value: 'call.connecting', description: 'A call is connecting' },
	{ name: 'Call Active', value: 'call.active', description: 'A call became active' },
	{ name: 'Call Ready', value: 'call.ready', description: 'A call media session is ready' },
	{ name: 'Answered Elsewhere', value: 'call.answered_elsewhere', description: 'A linked device answered the call' },
	{ name: 'Rejected Elsewhere', value: 'call.rejected_elsewhere', description: 'A linked device rejected the call' },
	{ name: 'Hangup Requested', value: 'call.hangup.requested', description: 'A hangup was requested' },
	{ name: 'Call Ending', value: 'call.ending', description: 'A call is ending' },
	{ name: 'Terminate Sent', value: 'call.terminate.sent', description: 'Terminate was sent to the provider' },
	{ name: 'Terminate Confirmed', value: 'call.terminate.confirmed', description: 'Terminate was confirmed' },
	{ name: 'Terminate Retry', value: 'call.terminate.retry', description: 'Terminate is being retried' },
	{ name: 'Terminate Failed', value: 'call.terminate.failed' },
	{ name: 'Call Ended', value: 'call.ended', description: 'A call ended' },
	{ name: 'Call Ended Unconfirmed', value: 'call.ended_unconfirmed', description: 'A call ended without remote terminate confirmation' },
	{ name: 'Video Playback Started', value: 'call.video.playback.started' },
	{ name: 'Video Playback Completed', value: 'call.video.playback.completed' },
	{ name: 'Video Playback Stopped', value: 'call.video.playback.stopped' },
	{ name: 'Video Playback Failed', value: 'call.video.playback.failed' },
	{ name: 'Recording Started', value: 'call.recording.started', description: 'A call recording started' },
	{ name: 'Recording Completed', value: 'call.recording.completed', description: 'A call recording completed' },
	{ name: 'Recording Partial', value: 'call.recording.partial', description: 'A partial recording was created' },
	{ name: 'Recording Failed', value: 'call.recording.failed', description: 'A call recording failed' },
	{ name: 'Recording Unavailable', value: 'call.recording.unavailable', description: 'A call recording is unavailable' },
	{ name: 'Recording Deleted', value: 'call.recording.deleted', description: 'A call recording was deleted' },
	{ name: 'Recording Expired', value: 'call.recording.expired', description: 'A call recording expired' },
];

export const GLOBAL_EVENT_OPTIONS: INodePropertyOptions[] = [
	{ name: 'Batch Created', value: 'message.batch.created', description: 'A message batch was created' },
	{ name: 'Batch Scheduled', value: 'message.batch.scheduled', description: 'A message batch was scheduled' },
	{ name: 'Batch Started', value: 'message.batch.started', description: 'A message batch started' },
	{ name: 'Batch Window Started', value: 'message.batch.window-started', description: 'A message batch sending window started' },
	{ name: 'Batch Waiting Window', value: 'message.batch.waiting-window', description: 'A message batch is waiting for its sending window' },
	{ name: 'Batch Recovered', value: 'message.batch.recovered', description: 'A message batch was recovered' },
	{ name: 'Batch Progress', value: 'message.batch.progress', description: 'A message batch reported progress' },
	{ name: 'Batch Pause Requested', value: 'message.batch.pause-requested', description: 'A pause was requested for a message batch' },
	{ name: 'Batch Paused', value: 'message.batch.paused', description: 'A message batch was paused' },
	{ name: 'Batch Waiting Instance', value: 'message.batch.waiting-instance', description: 'A message batch is waiting for an instance' },
	{ name: 'Batch Resumed', value: 'message.batch.resumed', description: 'A message batch was resumed' },
	{ name: 'Batch Stop Requested', value: 'message.batch.stop-requested', description: 'A stop was requested for a message batch' },
	{ name: 'Batch Stopped', value: 'message.batch.stopped', description: 'A message batch was stopped' },
	{ name: 'Batch Interrupted', value: 'message.batch.interrupted', description: 'A message batch was interrupted' },
	{ name: 'Batch Completed', value: 'message.batch.completed', description: 'A message batch completed' },
	{ name: 'Batch Completed With Errors', value: 'message.batch.completed-with-errors', description: 'A message batch completed with errors' },
	{ name: 'Batch Item Failed', value: 'message.batch.item.failed', description: 'A message batch item failed' },
	{ name: 'Batch Item Unknown', value: 'message.batch.item.unknown', description: 'A message batch item ended with unknown status' },
];
